//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2_bounding_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Replay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Replay()
        {
            this.Top_Five_Scores = new HashSet<Top_Five_Scores>();
        }
    
        public int replay_id { get; set; }
        public int bound_id { get; set; }
        public byte[] replay_name { get; set; }
        public Nullable<int> replay_difficulty { get; set; }
        public decimal replay_time { get; set; }
        public System.DateTime replay_date_complete { get; set; }
        public string submitter { get; set; }
        public string replay_player_name1 { get; set; }
        public string replay_player_name2 { get; set; }
        public string replay_player_name3 { get; set; }
        public string replay_player_name4 { get; set; }
        public string replay_player_name5 { get; set; }
        public string replay_player_name6 { get; set; }
        public string replay_player_name7 { get; set; }
        public string replay_player_name8 { get; set; }
    
        public virtual Bound Bound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Top_Five_Scores> Top_Five_Scores { get; set; }
    }
}
