//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2_bounding_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Top_Five_Scores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Top_Five_Scores()
        {
            this.User_Total_Points = new HashSet<User_Total_Points>();
        }
    
        public int bound_high_scores { get; set; }
        public Nullable<int> replay_id { get; set; }
        public Nullable<decimal> high_score1 { get; set; }
        public Nullable<decimal> high_score2 { get; set; }
        public Nullable<decimal> high_score3 { get; set; }
        public Nullable<decimal> high_score4 { get; set; }
        public Nullable<decimal> high_score5 { get; set; }
    
        public virtual Replay Replay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Total_Points> User_Total_Points { get; set; }
    }
}
